defaults:
  - _self_
  - /key

checkpoint:
  monitor: "val_pixel_auc"
  mode: "max"
  dirpath: "checkpoints_focal/"
  filename: SwinT-${experiment_name}-{epoch:02d}-{val_pixel_auc:.4f}
  save_top_k: 1
  save_last: true

early_stopping:
  monitor: "val_image_auc"
  mode: "max"
  patience: 10

lr_monitor:
  logging_interval: "epoch"